# Generated by Django 2.0.5 on 2020-01-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="configurationparameter",
            name="raw_value",
            field=models.TextField(blank=True),
        )
    ]
